### ISSUE TITLE
:LTCreateBookmarks not working.

### ISSUE THREAD

**Issue by MiscStuff839** [ldelossa/litee-bookmarks.nvim#4]
I ran the steps in the demo video by first creating a Notebook called config in my .config dir. When I run :LTCreateBookmark in my .config/nvim/init.vim I get the error
```
E5108: Error executing lua ...lugged/litee-bookmarks.nvim/lua/litee/bookmarks/init.lua:297: attempt to call field 'strip_path_prefix' (a nil value)
stack traceback:
        ...lugged/litee-bookmarks.nvim/lua/litee/bookmarks/init.lua:297: in function 'create_bookmark'
        [string ":lua"]:1: in main chunk
```
*NOTE to @ldelossa I copied your dotfile config for bookmarks but it still does not work*

**Comment by ldelossa** [comment]
@muppi090909 - you probably need to also update `litee.nvim`. That method was just added: https://github.com/ldelossa/litee.nvim/commit/c9fd775aebf702c81e2077693336584a0027d496

Keep in mind, anytime you update any litee-* plugin, you need to update `litee.nvim` too just to make sure you have the latest backing library. 

Also, make sure to read the latest README - this plugin has changed in the way it works in the last commit. This plug is very much a WIP so expect changes often.

**Comment by MiscStuff839** [comment]
This works now.

**Comment by muppi090909** [comment]
Also how do i jump to a bookmark 
*NOTE: I tried pressing enter on the bookmark in the notebook it just opens a new buffer with the bookmark name and symbol*
